### ISSUE TITLE
[Bug] Pathfinder buttons overlap on resize

### ISSUE THREAD

**Issue by jaredhenderson** [unimelb/design-system-issues#26]
#### Currently

At certain resolutions, pathfinder buttons overlap each other, which makes the text not look like it is centre aligned properly.

Example from bottom of page here: https://le.unimelb.edu.au/new-lms#jump5

![Screen Shot 2019-11-14 at 3.36.32 pm.png](https://images.zenhubusercontent.com/5acae0cd4b5806bc2bce3338/df15a120-7883-42cd-8e7a-9e233779f170)

#### Proposed solution

I'm a bit stumped here. I think the pathfinders would all behave a bit more predictably if they were converted to flex items, but I'm open to suggestions.

~- [ ] Delete all pathfinders~
- [ ] Refactor pathfinders so their sizing is consistent and they don't overlap

**Comment by dkevey** [comment]
@jaredh-um from memory there has always been a bug with the white/soft pathfinders when they are set to 4 (instead of 3). It's got to do with the padding on either side not being present on 4 boxes. (as it it's always been a bug). Would be nice to get it fixed if possible

https://resources.web.unimelb.edu.au/_nocache
![image](https://user-images.githubusercontent.com/1305804/69771333-8f22f200-11e0-11ea-8eb1-ddecc11f9dbe.png)

![image](https://user-images.githubusercontent.com/1305804/69771838-3a807680-11e2-11ea-9ebf-6bb059f441b3.png)

**Comment by jaredh-um** [comment]
@dkevey the grey line is a border-left that is only applied to the pathfinder-3 class apparently. You're correct that the pathfinder-4 class has multiple cascades of padding applied that eventually cancel out to 0 anyway. I'm struggling to understand the logic behind the amount of CSS for these pathfinders; to be honest I feel like the whole lot should be ditched and rewritten because it's such a mess.

Anyway, as an additional task for this ticket:
- [ ] Adjust padding values for pathfinder-4 classes to match pathfinder-3 values as necessary

**Comment by makenosound** [comment]
> to be honest I feel like the whole lot should be ditched and rewritten because it's such a mess.

This is definitely true. The pathfinder stuff is particularly hard to understand and super intertwined.

**Comment by jaredh-um** [comment]
@makenosound totally your call if you think the CSS for these should be completely scrapped. I feel like it could certainly be simplified/genericised across the different pathfinder types/amounts

**Comment by makenosound** [comment]
Yeah, it’s tricky. I think it could be rewritten to be _much_ simpler, but there are a bunch of versions out there in the wild that’ll be hard to test against (which is why I’d hesitated in the initial passes here).

**Comment by jaredh-um** [comment]
True. I wonder if @dkevey can provide some info on how these are used in a report or something?

**Comment by dkevey** [comment]
@jaredh-um since it's a pre-existing bug I think we should mark this one to refactor in Gen 4.
