### ISSUE TITLE
[BUG] 4 pathfinder with image background squished

### ISSUE THREAD

**Issue by rothenburycam** [unimelb/design-system-issues#27]
4 pathfinder with image background - looks very squashed. Note that 3 pathfinder with image looks fine. Title font also looks weird.

## Expected behaviour
Spacing should be consistent and aesthetic.

## Current behaviour
4 pathfinder with image background - looks very squashed. 

## Steps to reproduce
https://mspace.unimelb.edu.au/_recache#study-with-us
![Screen Shot 2019-11-15 at 3 42 20 pm](https://user-images.githubusercontent.com/11714609/68917509-af08ed80-07be-11ea-96f1-41cd7fc501e6.png)

### Affected browsers
- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] IE 11
- [ ] Safari 8+
- [ ] iOS 8.4+
- [ ] Android 4.4+

**Comment by jaredh-um** [comment]
@rothenburycam it appears the soft pathfinder class has a max-width applied to it that is not applied to other pathfinder types.

@makenosound can you check the following:
- [ ] The pathfinder-4 soft class has a max-width of 1100px set, overriding the usual max-width of 87.5rem. Can this lower width be removed?
- [ ] The H2 in the pathfinder section is inheriting a strange font-size because it is within a `full-width` tabbed section. Can you adjust this to 2rem to bring it in line with other H2s - font-family is addressed in another ticket.
