### ISSUE TITLE
[BUG] table data-labels incorrectly offset

### ISSUE THREAD

**Issue by woowoowoo** [unimelb/design-system-issues#33]
A complex table with double level headers causes data-label attributes to be assigned to the wrong column in the table body.

This table has a header row with a colspan of 4, and a second header row for the individual columns.
The JavasScript which generates the data-label attributes seems to be confused by the extra header, and assigns headers incorrectly to the subsequent columns.

![Screen Shot 2019-11-28 at 12 34 11 pm](https://user-images.githubusercontent.com/848310/69770106-d3f85a00-11db-11ea-914f-2aab607377fe.png)

This becomes particularly apparent when the table is linearised for mobile, and generated data-labels are displayed on the front end.

![Screen Shot 2019-11-28 at 12 39 16 pm](https://user-images.githubusercontent.com/848310/69770175-2d608900-11dc-11ea-9763-a395a8d0954a.png)

Attached is a text file with the source of this table before and after Design System javascript is applied.

## Possible solution

Tricky! Obviously, the javascript needs to be smarter about understanding table structure, but maybe the table structure should have been better in the first place. Have not tested it with manually set up 'header' attributes.

[table-header-problem.txt](https://github.com/unimelb/design-system-issues/files/3899452/table-header-problem.txt)

**Comment by gepifanio** [comment]
Hey @woowoowoo,

After analyzing the ticket and trying to work around how to get this done, we figured out that our tables at the moment are not ready to handle 2 rows of headings, which would mess up with the mobile view interface.

The suggestion instead of adding this new feature to handle 2 rows headings, would be better to use the `caption` tag after the `table` tag as shown in this example, this seems to make more sense. 
https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Advanced#adding_a_caption_to_your_table_with_caption

We would tackle this in new addition to the gen-4 new design system.
