### ISSUE TITLE
[Design] Page Listing content template needs styling options added

### ISSUE THREAD

**Issue by tblundell** [unimelb/design-system-issues#34]
Within the Martix environment, the "Page Listing" component outputs `<div>` when the Styling-> Presentation is set to Section.
The `div` wrapper has less top/bottom padding than 'section', and the extra space would be nice when using the `.alt` background.

## Expected behaviour
When selecting 'Section' in the dropdown options for Properties, the component in the outputted HTML should wrapped in a `<section>`  

## Current behaviour
Currently, selecting the  'Section'  in the dropdown options for Properties outputs a `div`.

<img width="389" alt="Screen Shot 2019-11-28 at 4 33 03 pm" src="https://user-images.githubusercontent.com/943446/69779651-d61ee080-11fc-11ea-8a18-47ec0df96fa8.png">

<img width="710" alt="Screen Shot 2019-11-28 at 4 34 18 pm" src="https://user-images.githubusercontent.com/943446/69779679-f484dc00-11fc-11ea-8f13-9aee31a4d8cf.png">

## Steps to reproduce

1. in Matrix create a Page Listing 
2. under the Styling heading, select 'Section' via the dropdown
3. create/save the component
4. check the browser Inspector to see output
 

### Affected browsers

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] IE 11
- [X] Safari 8+
- [ ] iOS 8.4+
- [ ] Android 4.4+

**Comment by dkevey** [comment]
Hi @tblundell the section classes and styles don't work when Content Templates are used. This is similar to #24  and we will look at implementing additional styling options inside the Content Template themselves to help with background colour and padding/margin. Marking this one for Gen 4 as we need to rework Content Templates anyway.

**Comment by dkevey** [comment]
@tblundell @jporich I've added in some styling options for the page listing content template so that you can style the heading and control some padding. https://resources.web.unimelb.edu.au/controlled-environment/content-templates/listing 
Be default the content template uses the `content-block` class so that should fix most issues by default without needing to go into the Edit Interface. I just need to do a wee bit more testing and update the documentation before I announce it on the slack channel.

Hopefully I have fixed most use cases, but let me know if I missed anything
![image](https://user-images.githubusercontent.com/1305804/71057197-fd3f5100-21af-11ea-8244-942e9e976a93.png)

**Comment by dkevey** [comment]
ok closing this one off as I've updated documentation https://resources.web.unimelb.edu.au/controlled-environment/news/merry-christmas
