### ISSUE TITLE
[BUG] <h2> elements not receiving white colour on blue background - "unit description"

### ISSUE THREAD

**Issue by jporich** [unimelb/design-system-issues#45]
Some odd cascading happening here:

We run a few systems that still run separate to Study - law is moving to transition to study but won't be ready in time for the 10th (I believe at the very least mdhs-study.unimelb.edu.au and potentially a few more Bespoke sites may be in the same boat)

On the "Subject description" accordions which open a blue background, the titles are appearing blue

## Expected behaviour

Titles should appear white.

Note: I'm actually a bit confused as the cascading rule _exists_ but it's being overrode by what appears to be a less scoped rule? 

![Screen Shot 2019-12-06 at 10 54 11 am](https://user-images.githubusercontent.com/10070570/70284411-ff9cc500-1817-11ea-95a5-1225b8a915e7.png)

## Current behaviour

There is a CSS rule:

`.uomcontent h1, .uomcontent h2, .uomcontent h3, .uomcontent h4, .uomcontent h5, .uomcontent h6 `
`{`
`    color: #012a58;`
`}`

Which is taking _precedence_ over the much more scoped rule:
`.uomcontent [role=main] table.course-progression tr td.unit-description`
`{`
`    color: #fff;`
`}`

Both in uom.css - indicated we've maybe had a class change or markup change somewhere???

## Steps to reproduce

1. https://law.unimelb.edu.au/study/single-subjects/masters#subject-list live example
2. Switch to gen 3 and open a subject accordion
3. Notice blue title - check the CSS rules vs Gen 1

### Affected browsers

Chrome, FF

## Possible solution

I can implement an override myself - this is some custom law stuff anyway so it's isolated out regardless (can target with custom IDs our external dev put in). But just worried there might be knock on effects elsewhere

Note: Seems to be markup related somehow but I can't determine why the `color:#fff` is detected but overrode - seems to have much more specific scope???

**Comment by jaredh-um** [comment]
Hey @jporich, I think it may be because we didn't have a specific colour generally assigned to headers previously. The selector you mentioned isn't targeting the H2 specifically, but rather any text in that cell, so it's being ignored in favour of the general colour set on the H2 which is more 'specific'. I think.

- [ ] Adjust the selector `.uomcontent [role="main"] table.course-progression tr td.unit-description h2` to include the property `color: white`

Also just FYI it looks like you have a custom .brightBlue class for some text spans in this section - obviously blue on blue won't be meeting contrast requirements very well. If you want to adjust that the colour palette is [here](https://zeroheight.com/17lwnkf17/p/261f11). There's also some faded text styles which probably don't work either but I'll leave the rest up to you.

**Comment by makenosound** [comment]
This should be fixed in https://github.com/unimelb/Gen3/pull/173

**Comment by tomstringer** [comment]
Thanks @makenosound - I'll close this off, but @jporich will need to fix up the remaining local styles.
