### ISSUE TITLE
Standardise alignment of margins when using class="half" component

### ISSUE THREAD

**Issue by tblundell** [unimelb/design-system-issues#8]
*** NOTE: 
- This is for responsive only (when 2 cols become 1)
- This is an enhancement for both versions of the brand design system (its apparent in 2 - so carried over to 3).

## Is the feature request related to a problem? Please describe. 
When viewing on a mobile/scaled small screen the 2 column layout has 3 margin depth settings, rather than one alignment. Effected elements are IMG, P, H2, and H3 (see screen grabs).
- IMG: the image scale is reduced, reducing image impact
- P: slightly narrower than standard` <p>` margins on other elements of page outside of "half" class
- H2 and H3 : not aligned with `<p>`, sitting inside from the margin.
See this page :https://le.unimelb.edu.au/flexap (or screenshots)

## Describe the solution you'd like 
Perhaps balanced margins on the LT and RT of the device, all the way down the page. This would  match the headers, paragraphs, etc that are not inside the 2 col "half" class. This 

## Describe alternatives you've considered 

nil

## Additional context 

**VER 3:**

<img width="377" alt="Screen Shot 2019-10-31 at 1 51 15 pm" src="https://user-images.githubusercontent.com/943446/67915976-724acd00-fbe8-11e9-85f9-c24fee86fb3e.png">

**VER 2:**

<img width="378" alt="Screen Shot 2019-10-31 at 1 57 42 pm" src="https://user-images.githubusercontent.com/943446/67915987-78d94480-fbe8-11e9-8d08-755561ae8d22.png">

** Elements on screen to illustrate margins (using red lines)  **
- content below the 'Flexap activity streams' header is within class="half"   

![screeshot-margins](https://user-images.githubusercontent.com/943446/67917075-edfa4900-fbeb-11e9-8254-6c5f31156f28.png)

**Comment by jaredh-um** [comment]
@makenosound mobile breakpoints seem to inherit desktop-specific properties that make the experience pretty inconsistent.

- [ ] There's a `width: 94%` set on most typographic elements. Do we need this? (we don't on mobile at least)

![Screen Shot 2019-11-05 at 10 21 41 am](https://user-images.githubusercontent.com/34703139/68168277-65e5bc00-ffbc-11e9-890b-c9ecf639421a.png)

- [ ] Images fill a single column on mobile better if the following properties are removed:
![Screen Shot 2019-11-05 at 10 44 55 am](https://user-images.githubusercontent.com/34703139/68168312-7e55d680-ffbc-11e9-9173-79397846f820.png)

However some of those properties are needed on desktop when it's two column as the images are too close to the text otherwise.

**Comment by makenosound** [comment]
I’ve addressed this in https://github.com/unimelb/Gen3/pull/173. Be good to confirm it’s working as expected for the example use case above, as it’s a little hard to test that scenario in the docs site.

**Comment by jaredh-um** [comment]
Looks good on the test URL. 👍

**Comment by tomstringer** [comment]
@tblundell Can we get you to have a look at this one and confirm if it's ok from your end?

**Comment by tblundell** [comment]
@tomstringer Looks great in the upcoming design systems styles. 👍

**Comment by tomstringer** [comment]
Whoop!
